name: url_launcher_example
description: Demonstrates how to use the url_launcher plugin.

dependencies:
  flutter:
    sdk: flutter
  url_launcher:
    path: ../

dev_dependencies:
  e2e: "^0.2.0"
  flutter_driver:
    sdk: flutter
  pedantic: ^1.8.0
  mockito: ^4.1.1
  plugin_platform_interface: ^1.0.0

flutter:
  uses-material-design: true
